// This file is generated by `flutterfire configure`.
// Run the following command in your project root AFTER placing your
// google-services.json and GoogleService-Info.plist files:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// That command will replace this file with your real Firebase configuration.
// See SETUP.md for full instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKzbadS6aTYgs3oz9w7bIDr1B4ht5Oas',
    appId: '1:30985386132:android:1eaf795f7af432018d9c81',
    messagingSenderId: '30985386132',
    projectId: 'cannonbutchery',
    storageBucket: 'cannonbutchery.firebasestorage.app',
  );

  // TODO: Replace with real values from `flutterfire configure`

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Bz3eh-npOIJxC4A1f2YwHKCdFjPmJps',
    appId: '1:30985386132:ios:d177098ea8cf83008d9c81',
    messagingSenderId: '30985386132',
    projectId: 'cannonbutchery',
    storageBucket: 'cannonbutchery.firebasestorage.app',
    iosClientId: '30985386132-693f6u240u051ea8h22vff142ac64pvs.apps.googleusercontent.com',
    iosBundleId: 'com.cannon.butchery.tracker',
  );

  // TODO: Replace with real values from `flutterfire configure`
}